services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
      - LOCALSTACK_DATA_DIR=/var/lib/localstack
    volumes:
      - "./setup-backend.sh:/etc/localstack/init/ready.d/setup-backend.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge